Repository BinaryStudioAcademy/bsa-2019-ide, pull requests merged in 2019-08, with the labels that each got.

#3 Feature/authentification api
  .vscode/launch.json
  .vscode/tasks.json
  backend/IDE.API/Controllers/AuthController.cs
  backend/IDE.API/Controllers/TokenController.cs
  backend/IDE.API/Extensions/ControllerBaseExtention.cs
  backend/IDE.API/Extensions/ServiceExtensions.cs
  backend/IDE.API/IDE.API.csproj
  backend/IDE.API/Startup.cs
  backend/IDE.API/Validators/RefreshTokenDTOValidator.cs
  backend/IDE.API/Validators/RevokeRefreshTokenDTOValidator.cs
  backend/IDE.API/appsettings.json
  backend/IDE.BLL/ExceptionsCustom/ExpiredRefreshTokenException.cs
  backend/IDE.BLL/ExceptionsCustom/InvalidTokenException.cs
  backend/IDE.BLL/ExceptionsCustom/InvalidUsernameOrPasswordException.cs
  backend/IDE.BLL/ExceptionsCustom/NotFoundException.cs
  backend/IDE.BLL/Helpers/UserExtention.cs
  backend/IDE.BLL/IDE.BLL.csproj
  backend/IDE.BLL/JWT/JWTFactory.cs
  backend/IDE.BLL/Services/AuthService.cs
  backend/IDE.Common/Authentification/AccessToken.cs
  backend/IDE.Common/Authentification/JwtIssuerOptions.cs
  backend/IDE.Common/DTO/Authentification/AccessTokenDTO.cs
  backend/IDE.Common/DTO/Authentification/RefreshTokenDTO.cs
  backend/IDE.Common/DTO/Authentification/RevokeRefreshTokenDTO.cs
  backend/IDE.Common/DTO/User/AuthUserDTO.cs
  backend/IDE.Common/DTO/User/UserDTO.cs
  backend/IDE.Common/DTO/User/UserLoginDTO.cs
  backend/IDE.Common/IDE.Common.csproj
  backend/IDE.Common/Security/SecurityHelper.cs
  backend/IDE.DAL/Entities/RefreshToken.cs
  backend/IDE.DAL/IDE.DAL.csproj
Labels: enhancement, fix-merge-conflicts

#9 Feature/http client wrapper
  backend/IDE.API/Startup.cs
  frontend/package-lock.json
  frontend/src/app/app.module.ts
  frontend/src/app/modules/landing/components/landing-root/landing-root.component.html
  frontend/src/app/modules/landing/components/landing-root/landing-root.component.ts
  frontend/src/app/services/http-client-wrapper.service.spec.ts
  frontend/src/app/services/http-client-wrapper.service.ts
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
  package-lock.json
Labels: enhancement

#12 added toastr package to project
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/modules/landing/components/landing-root/landing-root.component.html
  frontend/src/app/modules/landing/components/landing-root/landing-root.component.ts
  frontend/src/app/modules/landing/landing.module.ts
  frontend/src/styles.sass
Labels: enhancement

#11 Feature/blob container
  backend/IDE.API/Controllers/ArchivesBlobController.cs
  backend/IDE.API/Controllers/ValuesController.cs
  backend/IDE.API/Extensions/ServiceExtensions.cs
  backend/IDE.API/Startup.cs
  backend/IDE.API/appsettings.json
  backend/IDE.BLL/IDE.BLL.csproj
  backend/IDE.Common/Enums/ImageOwnerType.cs
  backend/IDE.DAL/Factories/Abstractions/IAzureBlobConnectionFactory.cs
  backend/IDE.DAL/Factories/AzureBlobConnectionFactory.cs
  backend/IDE.DAL/IDE.DAL.csproj
  backend/IDE.DAL/Repositories/Abstract/IBlobRepository.cs
  backend/IDE.DAL/Repositories/ArchivesBlobRepository.cs
Labels: fix-merge-conflicts

#14 Integrate UI with authentication
  backend/IDE.API/Controllers/AuthController.cs
  backend/IDE.API/Controllers/RegisterController.cs
  backend/IDE.API/Controllers/UsersController.cs
  backend/IDE.API/Extensions/ControllerBaseExtention.cs
  backend/IDE.API/Extensions/ServiceExtensions.cs
  backend/IDE.API/Startup.cs
  backend/IDE.API/appsettings.json
  backend/IDE.BLL/ExceptionsCustom/NotFoundException.cs
  backend/IDE.BLL/MappingProfiles/BuildProfile.cs
  backend/IDE.BLL/MappingProfiles/GitCredentiaProfile.cs
  backend/IDE.BLL/MappingProfiles/ImageProfile.cs
  backend/IDE.BLL/MappingProfiles/ProjectProfile.cs
  backend/IDE.BLL/MappingProfiles/UserProfile.cs
  backend/IDE.BLL/Services/UserService.cs
  backend/IDE.Common/DTO/Common/BuildDto.cs
  backend/IDE.Common/DTO/Common/GitCredentialDTO.cs
  backend/IDE.Common/DTO/Common/ImageDTO.cs
  backend/IDE.Common/DTO/Common/ProjectDTO.cs
  backend/IDE.Common/DTO/File/FileDTO.cs
  backend/IDE.Common/DTO/File/FileHistoryDTO.cs
  backend/IDE.Common/DTO/User/UserDTO.cs
  backend/IDE.Common/DTO/User/UserRegisterDTO.cs
  frontend/package-lock.json
  frontend/src/app/app.module.ts
  frontend/src/app/helpers/jwt.interceptor.ts
  frontend/src/app/models/auth/auth-user.ts
  frontend/src/app/models/auth/user-login-dto.ts
  frontend/src/app/models/auth/user-register-dto.ts
  frontend/src/app/models/common/auth-dialog-type.ts
  frontend/src/app/models/token/access-token-dto.ts
  frontend/src/app/models/token/access-token.ts
  frontend/src/app/models/token/auth-user.ts
  frontend/src/app/models/user.ts
  frontend/src/app/modules/authorization/authorization.module.ts
  frontend/src/app/modules/authorization/components/auth-dialog/auth-dialog.component.html
  frontend/src/app/modules/authorization/components/auth-dialog/auth-dialog.component.sass
  frontend/src/app/modules/authorization/components/auth-dialog/auth-dialog.component.spec.ts
  frontend/src/app/modules/authorization/components/auth-dialog/auth-dialog.component.ts
  frontend/src/app/nav-menu/nav-menu.component.html
  frontend/src/app/nav-menu/nav-menu.component.ts
  frontend/src/app/services/auth-dialog.service/auth-dialog.service.spec.ts
  frontend/src/app/services/auth-dialog.service/auth-dialog.service.ts
  frontend/src/app/services/auth.service/auth.service.ts
  frontend/src/app/services/event.service/event.service.spec.ts
  frontend/src/app/services/event.service/event.service.ts
  frontend/src/app/services/user.service/user.service.spec.ts
  frontend/src/app/services/user.service/user.service.ts
  frontend/src/index.html
  frontend/src/styles.sass
Labels: fix-merge-conflicts

#20 workspace created
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/app.component.sass
  frontend/src/app/modules/workspace/editor-section/editor-section.component.html
  frontend/src/app/modules/workspace/editor-section/editor-section.component.sass
  frontend/src/app/modules/workspace/editor-section/editor-section.component.spec.ts
  frontend/src/app/modules/workspace/editor-section/editor-section.component.ts
  frontend/src/app/modules/workspace/file-browser-section/file-browser-section.component.html
  frontend/src/app/modules/workspace/file-browser-section/file-browser-section.component.sass
  frontend/src/app/modules/workspace/file-browser-section/file-browser-section.component.spec.ts
  frontend/src/app/modules/workspace/file-browser-section/file-browser-section.component.ts
  frontend/src/app/modules/workspace/workspace-root/workspace-root.component.html
  frontend/src/app/modules/workspace/workspace-root/workspace-root.component.sass
  frontend/src/app/modules/workspace/workspace.module.ts
  frontend/src/styles.sass
Labels: enhancement

#21 Feature/dashhboard
  backend/IDE.API/Controllers/ProjectController.cs
  backend/IDE.API/Extensions/ServiceExtensions.cs
  backend/IDE.API/Properties/launchSettings.json
  backend/IDE.BLL/ExceptionsCustom/InvalidAuthorException.cs
  backend/IDE.BLL/Interfaces/IProjectService.cs
  backend/IDE.BLL/MappingProfiles/ProjectProfile.cs
  backend/IDE.BLL/Services/ProjectService.cs
  backend/IDE.Common/IDE.Common.csproj
  backend/IDE.Common/ModelsDTO/DTO/Project/ProjectDescriptionDTO.cs
  backend/IDE.Common/ModelsDTO/DTO/Project/projectCreateDTO.cs
  backend/IDE.DAL/Migrations/20190807115958_Init.cs
  frontend/.vscode/settings.json
  frontend/package-lock.json
  frontend/src/app/models/DTO/Project/projectCreateDTO.ts
  frontend/src/app/models/DTO/Project/projectDescriptionDTO.ts
  frontend/src/app/modules/authorization/models/auth-dialog-type.ts
  frontend/src/app/modules/authorization/models/compiler-type.ts
  frontend/src/app/modules/authorization/models/project-language.ts
  frontend/src/app/modules/authorization/models/project-type.ts
  frontend/src/app/modules/dashboard/components/all-projects/all-projects.component.html
  frontend/src/app/modules/dashboard/components/all-projects/all-projects.component.sass
  frontend/src/app/modules/dashboard/components/all-projects/all-projects.component.spec.ts
  frontend/src/app/modules/dashboard/components/all-projects/all-projects.component.ts
  frontend/src/app/modules/dashboard/components/assigned-projects/assigned-projects.component.html
  frontend/src/app/modules/dashboard/components/assigned-projects/assigned-projects.component.sass
  frontend/src/app/modules/dashboard/components/assigned-projects/assigned-projects.component.spec.ts
  frontend/src/app/modules/dashboard/components/assigned-projects/assigned-projects.component.ts
  frontend/src/app/modules/dashboard/components/dashboard-root/dashboard-root.component.html
  frontend/src/app/modules/dashboard/components/dashboard-root/dashboard-root.component.sass
  frontend/src/app/modules/dashboard/components/dashboard-root/dashboard-root.component.ts
  frontend/src/app/modules/dashboard/components/my-projects/my-projects.component.html
  frontend/src/app/modules/dashboard/components/my-projects/my-projects.component.sass
  frontend/src/app/modules/dashboard/components/my-projects/my-projects.component.spec.ts
  frontend/src/app/modules/dashboard/components/my-projects/my-projects.component.ts
  frontend/src/app/modules/dashboard/components/project-card/project-card.component.html
  frontend/src/app/modules/dashboard/components/project-card/project-card.component.sass
  frontend/src/app/modules/dashboard/components/project-card/project-card.component.spec.ts
  frontend/src/app/modules/dashboard/components/project-card/project-card.component.ts
  frontend/src/app/modules/dashboard/components/projects-list/projects-list.component.html
  frontend/src/app/modules/dashboard/components/projects-list/projects-list.component.sass
  frontend/src/app/modules/dashboard/components/projects-list/projects-list.component.spec.ts
  frontend/src/app/modules/dashboard/components/projects-list/projects-list.component.ts
  frontend/src/app/modules/dashboard/dashboard-routing.module.ts
  frontend/src/app/modules/dashboard/dashboard.module.ts
  frontend/src/app/modules/project/components/create-project/create-project.component.html
  frontend/src/app/modules/project/components/create-project/create-project.component.sass
  frontend/src/app/modules/project/components/create-project/create-project.component.spec.ts
  frontend/src/app/modules/project/components/create-project/create-project.component.ts
  frontend/src/app/modules/project/components/project-root/project-root.component.html
  frontend/src/app/modules/project/project-routing.module.ts
  frontend/src/app/modules/project/project.module.ts
  frontend/src/app/services/auth.service/auth.service.ts
  frontend/src/app/services/project.service/project.service.spec.ts
  frontend/src/app/services/project.service/project.service.ts
Labels: fix-merge-conflicts

#26 added few elements and appearance improvments
  frontend/src/app/modules/workspace/file-browser-section/file-browser-section.component.html
  frontend/src/app/modules/workspace/file-browser-section/file-browser-section.component.sass
  frontend/src/app/modules/workspace/workspace-root/workspace-root.component.html
  frontend/src/app/modules/workspace/workspace-root/workspace-root.component.sass
Labels: enhancement

#38 Feature/workspaceimprove
  frontend/src/app/modules/workspace/editor-section/editor-section.component.html
  frontend/src/app/modules/workspace/editor-section/editor-section.component.sass
  frontend/src/app/modules/workspace/editor-section/editor-section.component.ts
  frontend/src/app/modules/workspace/file-browser-section/file-browser-section.component.ts
  frontend/src/app/modules/workspace/workspace-root/workspace-root.component.html
  frontend/src/app/modules/workspace/workspace-root/workspace-root.component.ts
  frontend/src/app/modules/workspace/workspace.module.ts
  frontend/src/app/services/workspace.service.spec.ts
  frontend/src/app/services/workspace.service.ts
Labels: fix-merge-conflicts

#46 Feature/autosave
  frontend/src/app/guards/save-before-exit.guard.spec.ts
  frontend/src/app/guards/save-before-exit.guard.ts
  frontend/src/app/modules/workspace/editor-section/editor-section.component.ts
  frontend/src/app/modules/workspace/workspace-root/workspace-root.component.html
  frontend/src/app/modules/workspace/workspace-root/workspace-root.component.ts
  frontend/src/app/modules/workspace/workspace-routing.module.ts
  frontend/src/app/services/leave-page-dialog.service.spec.ts
  frontend/src/app/services/leave-page-dialog.service.ts
  frontend/src/app/services/workspace.service.ts
Labels: enhancement

#49 Feature/save button click
  frontend/src/app/modules/workspace/workspace-root/workspace-root.component.html
  frontend/src/app/modules/workspace/workspace-root/workspace-root.component.ts
Labels: enhancement

#76 Feature/editro changes to file
  frontend/src/app/models/DTO/File/fileCreateDTO.ts
  frontend/src/app/modules/workspace/editor-section/editor-section.component.ts
Labels: enhancement

#78 projects export with fake data and little enhancement in workspace
  backend/IDE.API/Controllers/ProjectController.cs
  backend/IDE.API/appsettings.json
  backend/IDE.BLL/Interfaces/IProjectService.cs
  backend/IDE.BLL/Services/ProjectService.cs
  backend/IDE.DAL/Factories/Abstractions/IAzureBlobConnectionFactory.cs
  backend/IDE.DAL/Factories/AzureBlobConnectionFactory.cs
  backend/IDE.DAL/Interfaces/IBlobRepository.cs
  backend/IDE.DAL/Repositories/ArchivesBlobRepository.cs
  frontend/src/app/models/DTO/File/fileCreateDTO.ts
  frontend/src/app/modules/workspace/file-browser-section/file-browser-section.component.ts
  frontend/src/app/modules/workspace/workspace-root/workspace-root.component.ts
Labels: enhancement

#95 Feature/proj export ui
  backend/IDE.API/Startup.cs
  backend/IDE.DAL/Migrations/20190815083335_Initial.Designer.cs
  backend/IDE.DAL/Migrations/20190820110807_AddMongoSeeding.Designer.cs
  backend/IDE.DAL/Migrations/IdeContextModelSnapshot.cs
  frontend/src/app/modules/project/components/project-details-info/project-details-info.component.html
  frontend/src/app/modules/project/components/project-details-info/project-details-info.component.sass
  frontend/src/app/modules/project/components/project-details-info/project-details-info.component.ts
  frontend/src/app/modules/workspace/file-browser-section/file-browser-section.component.ts
  frontend/src/app/modules/workspace/workspace-root/workspace-root.component.ts
  frontend/src/app/services/http-client-wrapper.service.ts
  frontend/src/app/services/project.service/project.service.ts
Labels: enhancement
